---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    errors_object:
      type: object
      properties:
        message:
          type: string
          example: Name can't be blank
    person:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: James Franco
        email:
          type: string
          example: acme@some.mail
        cpf:
          type: string
          example: 419.356.777-05
        address:
          type: string
          example: Mulholland Drive
        birthday:
          type: string
          pattern: "(?-mix:([0-9]{4})-(?:[0-9]{2})-([0-9]{2}))"
          example: '2019-05-17'
        active:
          type: boolean
    new_person:
      type: object
      properties:
        name:
          type: string
          example: James Franco
        email:
          type: string
          example: acme@some.mail
        cpf:
          type: string
          example: 419.356.777-05
        address:
          type: string
          example: Mulholland Drive
        birthday:
          type: string
          pattern: "(?-mix:([0-9]{4})-(?:[0-9]{2})-([0-9]{2}))"
          example: '2019-05-17'
        active:
          type: boolean
      required:
      - name
      - cpf
      - active
paths:
  "/people":
    post:
      summary: Creates a person
      tags:
      - People
      parameters: []
      responses:
        '201':
          description: Person Created
          content:
            application/json:
              example:
                id: 1
                name: James
                email: some@nice.mail
                address: Mulholland Drive
                cpf: 419.356.777-05
                birthday: '2019-05-17'
                active: true
        '422':
          description: Invalid Request
          content:
            application/json:
              example:
                message: 'Validation failed: Name can''t be blank'
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_person"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
