default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: eduardo
  password: teste123

development:
  <<: *default
  database: base_project_development

test:
  <<: *default
  database: base_project_test

production:
  <<: *default
  database: base_project_production
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV["DATABASE_POOL"] || 5 %>
  sslmode: require
