default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: joao
  password: 2521

development:
  <<: *default
  database: base_project_development

test:
  <<: *default
  database: base_project_test

production:
  <<: *default
  database: base_project_production
  user: joao
  password: 2521
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV["DATABASE_POOL"] || 5 %>
  sslmode: require
